### ISSUE TITLE
mp4 url 解析失效，新的解析方法TBD

### ISSUE THREAD

**Issue by ilove91** [ilove91/91dl#2]
目前91具体视频页面现在mp4 url渲染方式为

`document.write(strencode("Mix5QxIOJgctBycZAFoJXzt2CXgTHgxUfUlJTAMcPhYmDht4BRMxNyg/BTUfPwkDLBVjLCoyOw4ZHxM8H3V/NhcsPn0nSwNfBmsOfBYgExYFeBADYg1/DSFBaAZZAmsONAwhBxsWDyc5HnJ2Bz4DYxYNaEs6OC4rMAImVgY9EVgaHDs8GQk4NwZrRxEsJ1Qe","bd75vVlmwTecc7DfqDaHwVMb10q4LHYckdNIIyVNdUnBSF0wOQ2VfHvvTKxDR6JBthoRDxRfHXKIGNQEWHV50Y5blsYU8QZgaDIfJEUKiJ7GIjVRXw11tBEEyJtcezDaP/aLCNnAJYvf","Mix5QxIOJgctBycZAFoJXzt2CXgTHgxUfUlJTAMcPhYmDht4BRMxNyg/BTUfPwkDLBVjLCoyOw4ZHxM8H3V/NhcsPn0nSwNfBmsOfBYgExYFeBADYg1/DSFBaAZZAmsONAwhBxsWDyc5HnJ2Bz4DYxYNaEs6OC4rMAImVgY9EVgaHDs8GQk4NwZrRxEsJ1Qe"));`

strencode 为 http://91porn.com/js/md5.js 里的函数，上面代码实际等价于：

`document.write("<source src='http://198.255.82.90//mp43/311910.mp4?st=7q9BpRGAzE2h3mRi-bPxZA&e=1555576379' type='video/mp4'>");`

解决方法：

1. 破译91的encode方法
2. 下载js文件到本地，本地调用node获得mp4 url

最近没有时间，欢迎热心网友参与

**Comment by 5yan2cz** [comment]
document.write(strencode("MXx6EwcbcjgcNAMfKz0Dej0GAnRcKTR1dS1DCGhkWAQBfx9FPy0TRQhBCR4aKmhBUAcmLQ1MCBsHczxCAzNBFjEjJ2YgQhlbNAJ1OGF4LxlXGT5YFC9UP3oeCg4iKWZWfUc+PA0fHlQGHyg/LR4EJCMJGj8gRgU5DyV8OWkMA1I6ZhV/PFMWL1ZZODkALnMyD0JgDBRKEztRIQp/JDwFeAU8aGsDLQEDFD1sJD0VKV4mPnQiEFQtKSEyAhRrDAYdOn5YfXkCfS4qBwApAiElPiFhHDcSFTQwDUFhYmByAgAnFG0CIjo1HB0gQXEWDChnBRV8LzwcAQIQcH1kEBAkVBNaKh8TCiUbLgpyOi93V04=","a44ecC8RFgAeHPNCw4jD8auC9Tzb1VlqN+Y2qyZ0Qs0jVSQ53CwWA6YlH7urLptbRgvICqHbe0/p5Iej3Lt1qFeQ6JHtCE4f+vlEWfD9VHyHwtFhFeHmq+mHXc2q0akfvUWIiaXc2hTKcj1XYr2Fuzci0iiMFkWLHQQ9fxntpS6MqoMnkP2nIecoujnC9fO/h9aN7E7ggDtAOgURpQJOvBbjWq7634LTsQ72FbYqOgtEAYGRKBIWowDlY8/QsWqmYipoIMsmb8CM","MXx6EwcbcjgcNAMfKz0Dej0GAnRcKTR1dS1DCGhkWAQBfx9FPy0TRQhBCR4aKmhBUAcmLQ1MCBsHczxCAzNBFjEjJ2YgQhlbNAJ1OGF4LxlXGT5YFC9UP3oeCg4iKWZWfUc+PA0fHlQGHyg/LR4EJCMJGj8gRgU5DyV8OWkMA1I6ZhV/PFMWL1ZZODkALnMyD0JgDBRKEztRIQp/JDwFeAU8aGsDLQEDFD1sJD0VKV4mPnQiEFQtKSEyAhRrDAYdOn5YfXkCfS4qBwApAiElPiFhHDcSFTQwDUFhYmByAgAnFG0CIjo1HB0gQXEWDChnBRV8LzwcAQIQcH1kEBAkVBNaKh8TCiUbLgpyOi93V04=1"));

**Comment by 5yan2cz** [comment]
document.write(strencode("MXx6EwcbcjgcNAMfKz0Dej0GAnRcKTR1dS1DCGhkWAQBfx9FPy0TRQhBCR4aKmhBUAcmLQ1MCBsHczxCAzNBFjEjJ2YgQhlbNAJ1OGF4LxlXGT5YFC9UP3oeCg4iKWZWfUc+PA0fHlQGHyg/LR4EJCMJGj8gRgU5DyV8OWkMA1I6ZhV/PFMWL1ZZODkALnMyD0JgDBRKEztRIQp/JDwFeAU8aGsDLQEDFD1sJD0VKV4mPnQiEFQtKSEyAhRrDAYdOn5YfXkCfS4qBwApAiElPiFhHDcSFTQwDUFhYmByAgAnFG0CIjo1HB0gQXEWDChnBRV8LzwcAQIQcH1kEBAkVBNaKh8TCiUbLgpyOi93V04=","a44ecC8RFgAeHPNCw4jD8auC9Tzb1VlqN+Y2qyZ0Qs0jVSQ53CwWA6YlH7urLptbRgvICqHbe0/p5Iej3Lt1qFeQ6JHtCE4f+vlEWfD9VHyHwtFhFeHmq+mHXc2q0akfvUWIiaXc2hTKcj1XYr2Fuzci0iiMFkWLHQQ9fxntpS6MqoMnkP2nIecoujnC9fO/h9aN7E7ggDtAOgURpQJOvBbjWq7634LTsQ72FbYqOgtEAYGRKBIWowDlY8/QsWqmYipoIMsmb8CM","MXx6EwcbcjgcNAMfKz0Dej0GAnRcKTR1dS1DCGhkWAQBfx9FPy0TRQhBCR4aKmhBUAcmLQ1MCBsHczxCAzNBFjEjJ2YgQhlbNAJ1OGF4LxlXGT5YFC9UP3oeCg4iKWZWfUc+PA0fHlQGHyg/LR4EJCMJGj8gRgU5DyV8OWkMA1I6ZhV/PFMWL1ZZODkALnMyD0JgDBRKEztRIQp/JDwFeAU8aGsDLQEDFD1sJD0VKV4mPnQiEFQtKSEyAhRrDAYdOn5YfXkCfS4qBwApAiElPiFhHDcSFTQwDUFhYmByAgAnFG0CIjo1HB0gQXEWDChnBRV8LzwcAQIQcH1kEBAkVBNaKh8TCiUbLgpyOi93V04=1"));

**Comment by ilove91** [comment]
已解决
